runtime: nodejs16
instance_class: F1
automatic_scaling:
  min_instances: 1 # 最小インスタンス数
  max_instances: 1 # 最大インスタンス数
  min_idle_instances: 1 # アイドル状態インスタンスの最小数
  max_idle_instances: 1 # アイドル状態のインスタンスの最大数
